In [ ]:
from pytorch_tabnet.tab_model import TabNetClassifier
import numpy as np
import pandas as pd

train_data = pd.read_csv("train_set.csv", index_col=None)
test_data = pd.read_csv("test_set.csv", index_col=None)

X_train = train_data.drop(columns="truth")
y_train = train_data[['truth']]

X_test = test_data.drop(columns="truth")
y_test = test_data[['truth']]




In [ ]:
X_train.drop(columns=['Unnamed: 0', 'enroll_id'], inplace=True)
X_train

gender  education   age  prev_dropout_num  previous_enroll_num  \
0            1          0  27.0                 0                   12   
1            0          0  26.0                 0                    6   
2            1          0  25.0                 0                    5   
3            1          0  18.0                 0                    0   
4            0          4  18.0                 0                    7   
...        ...        ...   ...               ...                  ...   
157938       1          1  29.0                 2                  369   
157939       0          0  53.0                15                  367   
157940       1          0  24.0                 0                  377   
157941       0          2  23.0                 0                  379   
157942       0          0  20.0                 1                  378   

        previous_dropout_user_num  duration  session_num  video_num  \
0                               8       128            1         29   
1                               5        67            1          6   
2                               5       112            1         26   
3                               0       112            1         71   
4                               4       128            1          5   
...                           ...       ...          ...        ...   
157938                        331        71            7        941   
157939                        331        71           12        370   
157940                        336        71            9        930   
157941                        336        71           14        369   
157942                        336        71            3          4   

        courseware_num  
0                    1  
1                    3  
2                    5  
3                    2  
4                    1  
...                ...  
157938              82  
157939             168  
157940             532  
157941             370  
157942               9  

[157943 rows x 10 columns]

In [ ]:
X_test.drop(columns=['Unnamed: 0', 'enroll_id'], inplace=True)

In [ ]:
y_train.values.ravel()


array([1, 1, 0, ..., 0, 0, 0])

In [ ]:
X_train.values.ravel()

array([ 1.,  0., 27., ...,  3.,  4.,  9.])

In [ ]:
# Chuẩn bị dữ liệu (giả sử X_train, y_train đã được chuẩn bị)
clf = TabNetClassifier()
clf.fit(
    X_train.values, y_train.values.ravel(),
    max_epochs=200,
    patience=20,
    batch_size=1024,
    virtual_batch_size=128
)


c:\Users\baolo\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\pytorch_tabnet\abstract_model.py:82: UserWarning: Device used : cuda
  warnings.warn(f"Device used : {self.device}")
c:\Users\baolo\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\pytorch_tabnet\abstract_model.py:687: UserWarning: No early stopping will be performed, last training weights will be used.
  warnings.warn(wrn_msg)


epoch 0  | loss: 0.42309 |  0:00:04s
epoch 1  | loss: 0.3965  |  0:00:07s
epoch 2  | loss: 0.39046 |  0:00:11s
epoch 3  | loss: 0.38277 |  0:00:15s
epoch 4  | loss: 0.37789 |  0:00:19s
epoch 5  | loss: 0.37504 |  0:00:23s
epoch 6  | loss: 0.37291 |  0:00:27s
epoch 7  | loss: 0.37119 |  0:00:31s
epoch 8  | loss: 0.37133 |  0:00:35s
epoch 9  | loss: 0.3686  |  0:00:39s
epoch 10 | loss: 0.36592 |  0:00:43s
epoch 11 | loss: 0.36605 |  0:00:47s
epoch 12 | loss: 0.3656  |  0:00:51s
epoch 13 | loss: 0.36467 |  0:00:55s
epoch 14 | loss: 0.36433 |  0:00:59s
epoch 15 | loss: 0.36276 |  0:01:03s
epoch 16 | loss: 0.36329 |  0:01:07s
epoch 17 | loss: 0.36388 |  0:01:11s
epoch 18 | loss: 0.36265 |  0:01:14s
epoch 19 | loss: 0.36232 |  0:01:18s
epoch 20 | loss: 0.36242 |  0:01:22s
epoch 21 | loss: 0.36247 |  0:01:26s
epoch 22 | loss: 0.36167 |  0:01:30s
epoch 23 | loss: 0.36127 |  0:01:34s
epoch 24 | loss: 0.36086 |  0:01:38s
epoch 25 | loss: 0.36559 |  0:01:42s
epoch 26 | loss: 0.36312 |  0:01:46s
e

In [ ]:
preds = clf.predict(X_test.values)

In [ ]:
preds

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
from sklearn.metrics import classification_report

report = classification_report(y_test.values.ravel(), preds)

In [ ]:
print(report)

              precision    recall  f1-score   support

           0       0.79      0.51      0.62     16383
           1       0.86      0.96      0.90     51316

    accuracy                           0.85     67699
   macro avg       0.82      0.73      0.76     67699
weighted avg       0.84      0.85      0.84     67699

